/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DialogBoxes;

import javax.swing.JOptionPane;
import statics.Data;
import statics.DataCommunicator;

/**
 *
 * @author Jafari
 */
public class InsertData extends javax.swing.JDialog {
    
    private DataCommunicator DC;

    /**
     * Creates new form InsertData
     */
    public InsertData(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GMTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_insert = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PETF = new javax.swing.JTextField();
        GPETF = new javax.swing.JTextField();
        EPSTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        namadTF = new javax.swing.JTextField();
        bazar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        GMTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GMTFActionPerformed(evt);
            }
        });

        jLabel2.setText("قیمت میانگین");

        btn_insert.setText("Insert");
        btn_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_insertActionPerformed(evt);
            }
        });

        jLabel3.setText("P/E");

        jLabel4.setText("G P/E");

        jLabel5.setText("EPS");

        jLabel6.setText("بازار");

        PETF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PETFActionPerformed(evt);
            }
        });

        GPETF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GPETFActionPerformed(evt);
            }
        });

        EPSTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EPSTFActionPerformed(evt);
            }
        });

        jLabel1.setText("نماد");

        namadTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namadTFActionPerformed(evt);
            }
        });

        bazar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اصلی اول بورس", "فرعی اول بورس", "دوم بورس", "اول فرابورس", "ذوم فرابورس", "پایه زرد", "پایه نارنجی" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PETF)
                            .addComponent(EPSTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(GPETF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(namadTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(GMTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(bazar, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btn_insert, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(namadTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(GMTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(PETF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(GPETF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(EPSTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(bazar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_insert)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setDC(DataCommunicator DC) {
        this.DC = DC;
    }

    private void GMTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GMTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GMTFActionPerformed

    private void PETFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PETFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PETFActionPerformed

    private void GPETFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GPETFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GPETFActionPerformed

    private void EPSTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EPSTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EPSTFActionPerformed

    private void namadTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namadTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namadTFActionPerformed

    private void btn_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_insertActionPerformed
        if(!namadTF.getText().equals("")){
            Data data = new Data(namadTF.getText(),bazar.getSelectedItem().toString(),GMTF.getText(),PETF.getText(),GPETF.getText(),EPSTF.getText());
            DC.saveData(data);
            this.dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Can't save empty namad", "Can't Save!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn_insertActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EPSTF;
    private javax.swing.JTextField GMTF;
    private javax.swing.JTextField GPETF;
    private javax.swing.JTextField PETF;
    private javax.swing.JComboBox<String> bazar;
    private javax.swing.JButton btn_insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField namadTF;
    // End of variables declaration//GEN-END:variables
}
